### PR TITLE
Catch Throws from Non-Configurable Properties

### LINKED ISSUE #61: 3.x fails when the class contains non-configurable properties
We should add a try-catch there or be more careful copying descriptors.

### PR DESCRIPTION
**Pull request by DavidBrear**
This is in response to issues #61 where when defining properties with configurable set to false, the proxying process would throw the error: `TypeError: Cannot redefine property`. This fix adds a try catch around the places where properties are redefined and a test to verify that the proxy method contains the newly defined value. I am assuming the code should use the defined value on the updated Component (ie Component1 has non-configurable property 10 then update to Component2 which has non-configurable property 11 so the value should be 11).

Closes #61

### CODE REVIEW

File: src/createClassProxy.js [hunk 1]
```diff
@@ -148,7 +148,9 @@ function proxyClass(InitialComponent) {
         const savedDescriptor = savedDescriptors[key];
 
         if (!isEqualDescriptor(prevDescriptor, savedDescriptor)) {
-          Object.defineProperty(NextComponent, key, prevDescriptor);
+          try {
+            Object.defineProperty(NextComponent, key, prevDescriptor);
+          } catch (err) { }
```
Comment (wkwiatek) [inline src/createClassProxy.js]: I'd just add the comment into `catch` block what are the reasons for `try` block to fail.

File: src/createClassProxy.js [hunk 2]
```diff
@@ -164,8 +166,10 @@ function proxyClass(InitialComponent) {
 
       // Skip redefined descriptors
       if (prevDescriptor && savedDescriptor && !isEqualDescriptor(savedDescriptor, prevDescriptor)) {
-        Object.defineProperty(NextComponent, key, prevDescriptor);
-        Object.defineProperty(ProxyComponent, key, prevDescriptor);
+        try {
+          Object.defineProperty(NextComponent, key, prevDescriptor);
+          Object.defineProperty(ProxyComponent, key, prevDescriptor);
+        } catch (err) { }
```
Comment (wkwiatek) [inline src/createClassProxy.js]: Same here.

File: test/static-descriptor.js [hunk 3]
```diff
@@ -92,6 +92,24 @@ describe('static descriptor', () => {
       expect(() => proxy.update(ThrowingAccessors)).toNotThrow();
     });
 
+    it('replaces non-configurable properties', () => {
```
Comment (wkwiatek) [inline test/static-descriptor.js]: :+1:
